# Generated by Django 5.2.7 on 2025-11-19 01:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_column='documento', max_length=20, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('first_name', models.CharField(db_column='nombres', max_length=50)),
                ('last_name', models.CharField(db_column='apellidos', max_length=50)),
                ('email', models.EmailField(db_column='correo', max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(db_column='fecha_creacion', default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='users.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
