# Generated by Django 5.2.8 on 2025-11-23 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación de PQRS'), ('estado', 'Cambio de Estado'), ('respuesta', 'Respuesta al Cliente'), ('nota', 'Nota Interna')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'pqrs_evento',
                'ordering': ['-fecha_evento'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='PqrsHistorial',
        ),
        migrations.AlterModelOptions(
            name='pqrs',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='pqrsevento',
            name='pqrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pqrs.pqrs'),
        ),
        migrations.AddField(
            model_name='pqrsevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
