# Generated by Django 5.2.8 on 2025-11-24 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_pqrsevento_delete_pqrshistorial_alter_pqrs_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='pqrsevento',
            name='pqrs',
            field=models.ForeignKey(db_column='pqrs_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pqrs.pqrs'),
        ),
        migrations.AlterField(
            model_name='pqrsevento',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
