# Generated by Django 5.2.8 on 2025-11-19 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('costo_unitario_lote', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo promedio ponderado, calculado automáticamente.', max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_minimo', models.PositiveIntegerField(default=10)),
                ('stock_actual', models.PositiveIntegerField(default=0, help_text='Calculado automáticamente a partir de los lotes.')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
