# Generated by Django 5.2.8 on 2025-11-19 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('pse', 'PSE'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('consignacion', 'Consignación Bancaria')], default='efectivo', max_length=25)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reabastecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReabastecimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reabastecimiento_detalle',
                'managed': False,
            },
        ),
    ]
